-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "completedTripsCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "travelerLevel" TEXT NOT NULL DEFAULT 'EXPLORER';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "badges" TEXT[] DEFAULT ARRAY[]::TEXT[];
